In [16]:
#Import the libraries
import math
import numpy as np
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
from keras.models import Sequential
from keras.layers import Dense, LSTM
import matplotlib.pyplot as plt
plt.style.use('fivethirtyeight')

In [17]:
features1 = np.array(np.load('d:/faces/Person1/Normal/face_repr.npy'))
features2 = np.array(np.load('d:/faces/Person1/happy/face_repr.npy'))
features=np.concatenate((features1,features2))

print(features.shape)

(106, 1024)


In [18]:
#training_dataset_length = math.ceil(len(features) * .75)
training_dataset_length =10
print(training_dataset_length)

10


In [19]:
#Scale the all of the data to be values between 0 and 1 
scaler = MinMaxScaler(feature_range=(0, 1)) 
scaled_data = scaler.fit_transform(features)
features.shape

(106, 1024)

In [20]:
train_data = scaled_data[0:training_dataset_length  , : ]

#Splitting the data
x_train=np.concatenate((features[0:30],features[69:89])) #[1:11]
y_train = np.ones((2,50)) #[1,1,1,1,1,1,1,1,1,1]
print(x_train.shape)
y_train[0,30:]=0
y_train[1,0:29]=0
y_train=y_train.T
print(y_train)

#for i in range(10, len(train_data)):
    #x_train.append(train_data[i-10:i,0])
    #y_train.append(train_data[i,0])
 

(50, 1024)
[[1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]]


In [21]:
#Convert to numpy arrays
x_train, y_train = np.array(x_train), np.array(y_train)

#Reshape the data into 3-D array
x_train = np.reshape(x_train, (x_train.shape[0],x_train.shape[1],1))

In [22]:
from keras.layers import Dropout

# Initialising the RNN
model = Sequential()

model.add(LSTM(units = 50, return_sequences = True, input_shape = (1024, 1)))
model.add(Dropout(0.2))

# Adding a second LSTM layer and Dropout layer
model.add(LSTM(units = 50, return_sequences = True))
model.add(Dropout(0.2))

# Adding a third LSTM layer and Dropout layer
model.add(LSTM(units = 50, return_sequences = True))
model.add(Dropout(0.2))

# Adding a fourth LSTM layer and and Dropout layer
model.add(LSTM(units = 50))
model.add(Dropout(0.2))

# Adding the output layer
# For Full connection layer we use dense
# As the output is 1D so we use unit=1
model.add(Dense(units = 2))

In [23]:
#compile and fit the model on 30 epochs
model.compile(optimizer = 'adam', loss = 'mean_squared_error')
model.fit(x_train, y_train, epochs =50, batch_size = 50)

Epoch 1/50
50/50 [==============================] - 24s 471ms/step - loss: 0.5092
Epoch 2/50
50/50 [==============================] - 4s 78ms/step - loss: 0.4838
Epoch 3/50
50/50 [==============================] - 3s 65ms/step - loss: 0.4568
Epoch 4/50
50/50 [==============================] - 3s 68ms/step - loss: 0.4241
Epoch 5/50
50/50 [==============================] - 3s 65ms/step - loss: 0.3900
Epoch 6/50
50/50 [==============================] - 3s 61ms/step - loss: 0.3579
Epoch 7/50
50/50 [==============================] - 3s 62ms/step - loss: 0.3316
Epoch 8/50
50/50 [==============================] - 3s 58ms/step - loss: 0.2979
Epoch 9/50
50/50 [==============================] - 3s 58ms/step - loss: 0.2914
Epoch 10/50
50/50 [==============================] - 3s 69ms/step - loss: 0.2759
Epoch 11/50
50/50 [==============================] - 3s 60ms/step - loss: 0.2511
Epoch 12/50
50/50 [==============================] - 3s 62ms/step - loss: 0.2257
Epoch 13/50
50/50 [================

In [30]:
#Test data set
test_data = scaled_data[training_dataset_length - 10: , : ]

#splitting the x_test and y_test data sets
x_test = []
y_test =  features[training_dataset_length : , : ] 

#for i in range(10,len(test_data)):
    #x_test.append(test_data[i-10:i,0])
    
#Convert x_test to a numpy array 
x_test =np.concatenate((features[31:67],features[100:106]))
x_test=x_train
#x_test =features[100:106]
x_test = np.array(x_test)

#Reshape the data into 3-D array
x_test = np.reshape(x_test, (x_test.shape[0],x_test.shape[1],1))
y_test=[1,1,1]
print(x_test.shape) 


(50, 1024, 1)


In [31]:
#check predicted values
predictions = model.predict(x_test) 



In [32]:
print(predictions)
rmse=np.sqrt(np.mean(((predictions- y_test)**2)))
rmse



[[0.7307544  0.2827309 ]
 [0.73130274 0.2821444 ]
 [0.73163044 0.2818555 ]
 [0.7322879  0.28132728]
 [0.7325287  0.28110608]
 [0.73266506 0.28096333]
 [0.7327026  0.28092316]
 [0.73282844 0.28082547]
 [0.7328506  0.28080103]
 [0.7329011  0.28076127]
 [0.73297167 0.2807086 ]
 [0.73299587 0.2806846 ]
 [0.7330025  0.28067666]
 [0.733018   0.2806635 ]
 [0.73303044 0.2806522 ]
 [0.73303807 0.28064597]
 [0.7330412  0.2806426 ]
 [0.73304486 0.28064004]
 [0.7330463  0.28063887]
 [0.73304826 0.28063688]
 [0.7330489  0.2806365 ]
 [0.7330507  0.28063485]
 [0.73305106 0.2806345 ]
 [0.73305154 0.2806342 ]
 [0.7330518  0.28063387]
 [0.7330518  0.28063384]
 [0.73305213 0.28063366]
 [0.73305225 0.28063354]
 [0.73305225 0.28063348]
 [0.7330525  0.28063333]
 [0.7330532  0.28063282]
 [0.7330532  0.28063282]
 [0.7330532  0.28063282]
 [0.7330532  0.28063282]
 [0.7330532  0.28063282]
 [0.7330532  0.28063282]
 [0.7330532  0.28063282]
 [0.7330532  0.28063282]
 [0.7330532  0.28063282]
 [0.7330532  0.28063282]


ValueError: operands could not be broadcast together with shapes (50,2) (3,) 

In [13]:
#other tests
x_test= np.load('d:/faces/Person1/Normal/face_repr.npy')
x_test = np.array(x_test)
#x_test = MinMaxScaler(feature_range=(0, 1)) 
x_test = np.reshape(x_test, (x_test.shape[0],x_test.shape[1],1))
predictions = model.predict(x_test) 

In [14]:
predictions

array([[1.0178009],
       [1.0139829],
       [1.0185387],
       [1.0195675],
       [1.0146147],
       [1.0159515],
       [1.0141475],
       [1.017096 ],
       [1.0179207],
       [1.0164765],
       [1.0177388],
       [1.0162747],
       [1.0145141],
       [1.0111527],
       [1.0137037],
       [1.0149783],
       [1.017502 ],
       [1.018423 ],
       [1.0211189],
       [1.0188966],
       [1.0162677],
       [1.014932 ],
       [1.0179104],
       [1.018077 ]], dtype=float32)

In [14]:
print(x_test)

[[-0.03317452  0.02461971  0.07817355 ...  0.00781967 -0.02200413
   0.00174987]
 [-0.03084525  0.02794943  0.08092289 ... -0.00420234 -0.00380496
  -0.00387159]
 [-0.00918369  0.05201913  0.10367122 ...  0.000689   -0.00537141
   0.01241956]
 ...
 [-0.03607735  0.03372759  0.10282868 ... -0.01260461 -0.04441839
   0.00993899]
 [-0.03301831  0.04360268  0.09816383 ... -0.00620522 -0.03252188
  -0.00737865]
 [-0.0323858   0.02097484  0.08453061 ...  0.01415588 -0.0325042
   0.01263599]]


In [16]:
np.shape(x_test)
np.shape(x_train)

(1, 10, 1)

In [18]:
print(x_train)

[[[0.22451591]
  [0.        ]
  [0.19601765]
  [0.24201467]
  [0.5045395 ]
  [0.02253823]
  [0.48225734]
  [0.80237682]
  [0.80035761]
  [0.61944591]]]


In [21]:
print(y_train)
print(np.shape(train_data))

[0.70714601]
(11, 128)


In [26]:
len(train_data)

11

In [28]:
x_train.shape[1]

10

In [29]:
y_train.shape

(1,)

In [30]:
np.size(y_train)

1

In [7]:
x_train.shape[1]

128

In [10]:
x_train.shape

(14, 128, 1)

In [14]:
x_test.shape

(3, 10, 1)

In [20]:
x_train=features[1:10]
print(x_train.shape)

(9, 128)
